### ISSUE TITLE
Add API key for frontend

### ISSUE THREAD

**Issue by rekibnikufesin** [computablelabs/ffa-datatrust#10]
Add an API key to the server that can be used by the frontend app to validate requests. This will help fend off script kiddies and spam attacks with minimal requirements on the API. 
- [ ] Add API key support to API server
- [ ] Store API key(s?) in AWS Secrets
- [ ] Provide key to frontend app
- [ ] Add test to ensure valid/invalid keys exhibit the proper behavior

**Comment by thirtyaughtsix** [comment]
you know i was thinking can't we put this in `nginx.conf`?  definitely want to keep the `x-api-key` out of the FE code.  and it has no effect for local runs.
