### ISSUE TITLE
Computable.py Integration for Listing

### ISSUE THREAD

**Issue by robrobbins** [computablelabs/ffa-datatrust#14]
Once a client has initiated an upload it's up to the datatrust to initially validate the data and call to 

* datatustContract.setDataHash

For a listing candidate.

There may be some supporting getters that a datatrust may want to use around candidates and the Voting contract like

* voting.isCandidate
* voting.pollClosed

etc...

It may also be that datatrust can split out separate tickets for candidate concerns

**Comment by rekibnikufesin** [comment]
Implement via celery worker:
if pollEnded is true we know you can't vote anymore

you can see yea and nay votes
a datatrust could know right then if it passed or failed
act on its own behalf (not call resolve)
maybe that's the better pattern?
so the datatrust can purge/move candidates without resolving them
weeee
#async
if i ran a datatrust -- that's prob what i'd do
i ain't spendin no .025 cents
