### ISSUE TITLE
`voting.deployed.getPastEvents` call for fetching candidates

### ISSUE THREAD

**Issue by thirtyaughtsix** [computablelabs/ffa-datatrust#26]
Need to do a `getPastEvents` call on Votng.deployed looking for the `'CandidateAdded'` event.  Then need to fill out those return dicts with their metadata from dynamo.

Old but related Typescript code:
```
    const filter = {
      filter: {
        owner: ethereum.selectedAddress,
      },
      fromBlock,
      toBlock: latestBlock,
    }

    const voting = await VotingModule.getVoting(account, web3)
    const ethereumEvents = await voting.deployed!.getPastEvents('CandidateAdded', filter) as EthereumEvent[]
    return ethereumEvents.map((ee) => ProtocolModule.ethereumEventToFfaListing(ee))
```

See #25

**Comment by robrobbins** [comment]
* `ethereum.selectedAddress` === user's public key

so @rekibnikufesin will not have the MM `ethereum.selectedAddress` available but he will have other ways to have access to the user's public key - likely from a URL or the FE passing it to him

* `fromBlock` above defaults to `0`.

The fact that i used a var in the declaration was hinting at "block paging"

* `ethereumEventToFfaListing` is obviously some FE specific stuff -- @rekibnikufesin will likely just be sending back the actual events themselves, but _idk_...

**Comment by robrobbins** [comment]
done in capi
