### ISSUE TITLE
Provide endpoint for candidates by owner

### ISSUE THREAD

**Issue by rekibnikufesin** [computablelabs/ffa-datatrust#29]
Much like #8, provide an endpoint to retrieve all candidates for a specified owner.

URL parameter `/candidates/{owner public key}/` 
Query string `block` (optional) - block number to retrieve candidates since (default=0)
attach metadata from protocol
attach metadata from dynamo
Return listings in a standardized format

**Comment by robrobbins** [comment]
done in capi
