### ISSUE TITLE
endpoint for listed item purchase count

### ISSUE THREAD

**Issue by thirtyaughtsix** [computablelabs/ffa-datatrust#45]
See [figma v4](https://www.figma.com/file/cakBXdrJavD5KIb4jrea7F/ffa-v4?node-id=0%3A1)

Is this necessary?  Or should FE just do this as a log grep?

**Comment by robrobbins** [comment]
it'll be a log grep.

caveat.

the event does not exist yet:

https://github.com/computablelabs/computable/blob/master/contracts/Datatrust.vy#L239

is where it will go and it will be `ListingAccessed` Event with the exact args that go to that method:
-> `ListingAccessed(listing_hash, delivery_hash, amount_accessed)`

I had a TODO somewhere about should i write this event. Answer seems to be yes. I'll put a ticket in for the 917 milestone (though it will be protocol not datatrust)
